### ISSUE TITLE
babel6 and babel7?

### ISSUE THREAD

**Issue by StevenACoffman** [mromarreyes/scorpion-encounters#1]
I am confused by your package.json including both versions of babel but no `.babelrc`
I would think your package.json should be more like this:
```
    "@babel/core": "7.2.2",
    "@babel/preset-env": "7.3.1",
    "babel-core": "^7.0.0-bridge.0",
    "babel-loader": "^8.0.0",
```
### `.babelrc`:
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "8.10"
        }
      }
    ]
  ]
}
``

**Comment by mromarreyes** [comment]
@StevenACoffman ,
Removed the unnecessary babel-core dev dependency. Thank you. 
Correct me if I'm wrong but I did not find that I needed a .babelrc file.

```
"devDependencies": {
    "@babel/core": "^7.2.2",
    "babel-loader": "^8.0.5",
    "serverless-webpack": "^5.2.0",
    "webpack": "^4.29.3",
    "webpack-node-externals": "^1.7.2"
  },
```

**Comment by StevenACoffman** [comment]
Without a .babelerc with preset env:
> Sidenote, if no targets are specified, @babel/preset-env will transform all ECMAScript 2015+ code by default.

> We don't recommend using preset-env this way because it doesn't take advantage of its ability to target specific browsers.

So you might either transpile to an incorrect target

**Comment by mromarreyes** [comment]
@StevenACoffman Thank you I learned something new 👍 . This has been added.
